//! CPython C-Extension Module Code Generator.
//!
//! Generates C source containing CPython C-API bindings (`PyMethodDef`,
//! `PyModuleDef`, and `PyInit_<name>`) to compile IRIS modules directly
//! into native Python extension modules (`.pyd` on Windows, `.so` on Linux/macOS).

use std::fmt::Write;

use crate::error::CodegenError;
use crate::ir::module::IrModule;
use crate::ir::types::{DType, IrType};

/// Emits complete C source for a CPython C-extension module wrapping the IRIS module.
pub fn emit_python_ext(module: &IrModule) -> Result<String, CodegenError> {
    let module_name = if module.name.is_empty() {
        "iris_ext"
    } else {
        &module.name
    };

    let mut out = String::new();

    writeln!(
        out,
        "/* Generated by IRIS Compiler — CPython C-Extension Module */"
    )?;
    writeln!(out, "#define PY_SSIZE_T_CLEAN")?;
    writeln!(out, "#include <Python.h>")?;
    writeln!(out, "#include <stdint.h>")?;
    writeln!(out, "#include <stdbool.h>")?;
    writeln!(out)?;

    // Filter exportable functions
    let export_fns: Vec<_> = module
        .functions()
        .iter()
        .filter(|f| {
            !f.name.starts_with('_')
                && f.name != "main"
                && !f.name.contains("__")
                && !f.name.is_empty()
        })
        .collect();

    // 1. Forward declarations of IRIS native functions
    writeln!(out, "/* ── IRIS Native Function Declarations ── */")?;
    for func in &export_fns {
        let ret_c_ty = c_type_for_ir(&func.return_ty);
        let params_c_ty: Vec<String> = func
            .params
            .iter()
            .map(|p| format!("{} {}", c_type_for_ir(&p.ty), p.name))
            .collect();
        let params_sig = if params_c_ty.is_empty() {
            "void".to_string()
        } else {
            params_c_ty.join(", ")
        };
        writeln!(out, "extern {} {}({});", ret_c_ty, func.name, params_sig)?;
    }
    writeln!(out)?;

    // 2. Python wrapper functions
    writeln!(out, "/* ── CPython Method Wrappers ── */")?;
    for func in &export_fns {
        writeln!(
            out,
            "static PyObject* py_{}(PyObject* self, PyObject* args) {{",
            func.name
        )?;
        let _ = "self"; // silence unused

        if func.params.is_empty() {
            writeln!(out, "    (void)self;")?;
            writeln!(out, "    (void)args;")?;
            if matches!(func.return_ty, IrType::Tuple(ref ts) if ts.is_empty()) {
                writeln!(out, "    {}();", func.name)?;
                writeln!(out, "    Py_RETURN_NONE;")?;
            } else {
                let ret_ty = c_type_for_ir(&func.return_ty);
                writeln!(out, "    {} result = {}();", ret_ty, func.name)?;
                let ret_expr = py_box_expr("result", &func.return_ty);
                writeln!(out, "    return {};", ret_expr)?;
            }
        } else {
            let mut format_str = String::new();
            let mut decls = Vec::new();
            let mut parse_ptrs = Vec::new();
            let mut call_args = Vec::new();

            for (i, param) in func.params.iter().enumerate() {
                let var_name = format!("arg_{}", i);
                let (fmt_ch, c_ty) = py_arg_format(&param.ty);
                format_str.push_str(fmt_ch);
                decls.push(format!("    {} {};", c_ty, var_name));
                parse_ptrs.push(format!("&{}", var_name));
                call_args.push(var_name);
            }

            for decl in decls {
                writeln!(out, "{}", decl)?;
            }

            writeln!(
                out,
                "    if (!PyArg_ParseTuple(args, \"{}\", {})) {{",
                format_str,
                parse_ptrs.join(", ")
            )?;
            writeln!(out, "        return NULL;")?;
            writeln!(out, "    }}")?;

            if matches!(func.return_ty, IrType::Tuple(ref ts) if ts.is_empty()) {
                writeln!(out, "    {}({});", func.name, call_args.join(", "))?;
                writeln!(out, "    Py_RETURN_NONE;")?;
            } else {
                let ret_ty = c_type_for_ir(&func.return_ty);
                writeln!(
                    out,
                    "    {} result = {}({});",
                    ret_ty,
                    func.name,
                    call_args.join(", ")
                )?;
                let ret_expr = py_box_expr("result", &func.return_ty);
                writeln!(out, "    return {};", ret_expr)?;
            }
        }

        writeln!(out, "}}")?;
        writeln!(out)?;
    }

    // 3. PyMethodDef table
    writeln!(out, "/* ── Module Method Table ── */")?;
    writeln!(out, "static PyMethodDef {}Methods[] = {{", module_name)?;
    for func in &export_fns {
        writeln!(
            out,
            "    {{\"{}\", py_{}, METH_VARARGS, \"Compiled IRIS function: {}\"}},",
            func.name, func.name, func.name
        )?;
    }
    writeln!(out, "    {{NULL, NULL, 0, NULL}}")?;
    writeln!(out, "}};")?;
    writeln!(out)?;

    // 4. PyModuleDef struct
    writeln!(out, "/* ── Module Definition ── */")?;
    writeln!(out, "static struct PyModuleDef {}_module = {{", module_name)?;
    writeln!(out, "    PyModuleDef_HEAD_INIT,")?;
    writeln!(out, "    \"{}\",", module_name)?;
    writeln!(out, "    \"IRIS Autonomous Native Extension Module\",",)?;
    writeln!(out, "    -1,")?;
    writeln!(out, "    {}Methods", module_name)?;
    writeln!(out, "}};")?;
    writeln!(out)?;

    // 5. PyInit entry point
    writeln!(out, "/* ── Module Initialization Entry Point ── */")?;
    writeln!(out, "PyMODINIT_FUNC PyInit_{}(void) {{", module_name)?;
    writeln!(out, "    return PyModule_Create(&{}_module);", module_name)?;
    writeln!(out, "}}")?;

    Ok(out)
}

fn c_type_for_ir(ty: &IrType) -> &'static str {
    match ty {
        IrType::Scalar(DType::I64) | IrType::Scalar(DType::U64 | DType::USize) => "int64_t",
        IrType::Scalar(DType::I32) | IrType::Scalar(DType::U32) => "int32_t",
        IrType::Scalar(DType::I8) | IrType::Scalar(DType::U8) => "int8_t",
        IrType::Scalar(DType::F64) => "double",
        IrType::Scalar(DType::F32) => "float",
        IrType::Scalar(DType::Bool) => "bool",
        IrType::Str => "const char*",
        _ => "void*",
    }
}

fn py_arg_format(ty: &IrType) -> (&'static str, &'static str) {
    match ty {
        IrType::Scalar(DType::I64) | IrType::Scalar(DType::U64 | DType::USize) => {
            ("L", "long long")
        }
        IrType::Scalar(DType::I32) | IrType::Scalar(DType::U32) => ("i", "int"),
        IrType::Scalar(DType::F64) | IrType::Scalar(DType::F32) => ("d", "double"),
        IrType::Scalar(DType::Bool) => ("p", "int"),
        IrType::Str => ("s", "const char*"),
        _ => ("O", "PyObject*"),
    }
}

fn py_box_expr(val_name: &str, ty: &IrType) -> String {
    match ty {
        IrType::Scalar(DType::I64) | IrType::Scalar(DType::U64 | DType::USize) => {
            format!("PyLong_FromLongLong((long long){})", val_name)
        }
        IrType::Scalar(DType::I32) | IrType::Scalar(DType::U32) => {
            format!("PyLong_FromLong((long){})", val_name)
        }
        IrType::Scalar(DType::F64) | IrType::Scalar(DType::F32) => {
            format!("PyFloat_FromDouble((double){})", val_name)
        }
        IrType::Scalar(DType::Bool) => {
            format!("PyBool_FromLong({} ? 1 : 0)", val_name)
        }
        IrType::Str => {
            format!("PyUnicode_FromString({})", val_name)
        }
        _ => "Py_None; Py_INCREF(Py_None)".to_string(),
    }
}
